"""Add user_code and address columns to Clients

Revision ID: a6b0d01dfc49
Revises: 
Create Date: 2024-10-04 21:04:38.660676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b0d01dfc49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('user_code')

    # ### end Alembic commands ###
