password_policy:
  min_length: 10  # Increase the minimum length to 10
  complexity:
    uppercase: true  
    lowercase: true  
    digits: true  
    special_characters: true  
  history_limit: 3  
  dictionary_check: false  
login_attempts_limit: 3
